### ISSUE TITLE
Denver, Colorado missing

### ISSUE THREAD

**Issue by dolan-a** [reflect/amazon-hq2-proposals#3]
I know Denver sent a proposal, but I don't have any resources handy to share.

**Comment by bradhe** [comment]
@pydolan great idea filing issues for ones that are missing that we know are indeed out there. Assigning this to me & @sprokusk to see if we can find it somewhere.

**Comment by sebastian-adam** [comment]
Apologies for never resolving this issue. At the time that the question was asked we had posted all of the proposals our two-person team could find. Unfortunately this repository is no longer maintained, though feel free to reach out should anyone care to pick up where we left off. Thanks.
