### ISSUE TITLE
Highlight proposals that made the cut

### ISSUE THREAD

**Issue by turoczy** [reflect/amazon-hq2-proposals#6]
Now that there is a shortlist, it would be interesting to indicate who made the cut on the map and in the list. 

Shortlist cities:

- Atlanta, GA
- Austin, TX
- Boston, MA
- Chicago, IL
- Columbus, OH
- Dallas, TX
- Denver, CO
- Indianapolis, IN
- Los Angeles, CA
- Miami, FL
- Montgomery County, MD
- Nashville, TN
- Newark, NJ
- New York City, NY
- Northern Virginia
- Philadelphia, PA
- Pittsburgh, PA
- Raleigh, NC
- Toronto, ON, Canada
- Washington, DC

**Comment by bradhe** [comment]
Thanks for the suggestion! I called out the cities specifically that made it to the short list (of those that we had, at least--we're still missing quite a few of them).

Great idea.
